/*
* Copyright (c) 2023, Lawrence Livermore National Security, LLC. Produced at the Lawrence Livermore National Laboratory
* CODE-743439.
* All rights reserved.
* This file is part of CCT. For details, see https://github.com/LLNL/coda-calibration-tool.
*
* Licensed under the Apache License, Version 2.0 (the “Licensee”); you may not use this file except in compliance with the License.  You may obtain a copy of the License at:
* http://www.apache.org/licenses/LICENSE-2.0
* Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an “AS IS” BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and limitations under the license.
*
* This work was performed under the auspices of the U.S. Department of Energy
* by Lawrence Livermore National Laboratory under Contract DE-AC52-07NA27344.
*/
package gov.llnl.gnem.apps.coda.calibration.gui;

public class AboutText {

    public static final String LICENSE_INFO = "Coda Calibration Tool (CCT) & Coda Envelope Ratio Tool (CERT)\r\n\n"
            + "Copyright (c) 2023, Lawrence Livermore National Security, LLC. Produced at the Lawrence Livermore National Laboratory\r\n"
            + "CODE-743439.\r\n"
            + "All rights reserved.\r\n"
            + "For details, see https://github.com/LLNL/coda-calibration-tool.\r\n"
            + "\r\n"
            + "Licensed under the Apache License, Version 2. You may obtain a copy of the License at:\r\n"
            + "http://www.apache.org/licenses/LICENSE-2.0\r\n"
            + "Unless required by applicable law or agreed to in writing, software distributed under the License is distributed\r\n"
            + "on an “AS IS” BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\r\n"
            + "See the License for the specific language governing permissions and limitations under the license.\r\n"
            + "\r\n"
            + "This work was performed under the auspices of the U.S. Department of Energy\r\n"
            + "by Lawrence Livermore National Laboratory under Contract DE-AC52-07NA27344.\r\n"
            + "\r\nOPEN SOURCE COMPONENTS / LIBRARIES / CODE:\r\n\n"
            + "Apache Software License, Version 2.0:\r\n"
            + "    ClassMate (com.fasterxml:classmate:1.5.1 - https://github.com/FasterXML/java-classmate)\r\n"
            + "    Jakarta Bean Validation API (jakarta.validation:jakarta.validation-api:2.0.2 - https://beanvalidation.org)\r\n"
            + "    Jackson-annotations (com.fasterxml.jackson.core:jackson-annotations:2.13.3 - http://github.com/FasterXML/jackson)\r\n"
            + "    Jackson-core (com.fasterxml.jackson.core:jackson-core:2.13.3 - https://github.com/FasterXML/jackson-core)\r\n"
            + "    Jackson-databind (com.fasterxml.jackson.core:jackson-databind:2.13.3 - http://github.com/FasterXML/jackson)\r\n"
            + "    Jackson-dataformat-YAML (com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.3 - https://github.com/FasterXML/jackson-dataformats-text)\r\n"
            + "    Jackson datatype: jdk8 (com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.13.3 - https://github.com/FasterXML/jackson-modules-java8/jackson-datatype-jdk8)\r\n"
            + "    Jackson datatype: JSR310 (com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.3 - https://github.com/FasterXML/jackson-modules-java8/jackson-datatype-jsr310)\r\n"
            + "    Jackson-module-parameter-names (com.fasterxml.jackson.module:jackson-module-parameter-names:2.13.3 - https://github.com/FasterXML/jackson-modules-java8/jackson-module-parameter-names)\r\n"
            + "    FindBugs-jsr305 (com.google.code.findbugs:jsr305:3.0.2 - http://findbugs.sourceforge.net/)\r\n"
            + "    Error-prone annotations (com.google.errorprone:error_prone_annotations:2.11.0 - https://errorprone.info/error_prone_annotations)\r\n"
            + "    Guava InternalFutureFailureAccess and InternalFutures (com.google.guava:failureaccess:1.0.1 - https://github.com/google/guava/failureaccess)\r\n"
            + "    Guava: Google Core Libraries for Java (com.google.guava:guava:31.1-jre - https://github.com/google/guava)\r\n"
            + "    Guava ListenableFuture only (com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava - https://github.com/google/guava/listenablefuture)\r\n"
            + "    J2ObjC Annotations (com.google.j2objc:j2objc-annotations:1.3 - https://github.com/google/j2objc/)\r\n"
            + "    JSON.simple (com.googlecode.json-simple:json-simple:1.1.1 - http://code.google.com/p/json-simple/)\r\n"
            + "    project ':json-path' (com.jayway.jsonpath:json-path:2.7.0 - https://github.com/jayway/JsonPath)\r\n"
            + "    JSON library from Android SDK (com.vaadin.external.google:android-json:0.0.20131108.vaadin1 - http://developer.android.com/sdk)\r\n"
            + "    HikariCP (com.zaxxer:HikariCP:4.0.3 - https://github.com/brettwooldridge/HikariCP)\r\n"
            + "    IO (commons-io:commons-io:1.3.1 - http://jakarta.apache.org/commons/io/)\r\n"
            + "    Logging (commons-logging:commons-logging:1.0.4 - http://jakarta.apache.org/commons/logging/)\r\n"
            + "    micrometer-core (io.micrometer:micrometer-core:1.9.2 - https://github.com/micrometer-metrics/micrometer)\r\n"
            + "    Netty/Buffer (io.netty:netty-buffer:4.1.79.Final - https://netty.io/netty-buffer/)\r\n"
            + "    Netty/Codec (io.netty:netty-codec:4.1.79.Final - https://netty.io/netty-codec/)\r\n"
            + "    Netty/Codec/DNS (io.netty:netty-codec-dns:4.1.79.Final - https://netty.io/netty-codec-dns/)\r\n"
            + "    Netty/Codec/HTTP (io.netty:netty-codec-http:4.1.79.Final - https://netty.io/netty-codec-http/)\r\n"
            + "    Netty/Codec/HTTP2 (io.netty:netty-codec-http2:4.1.79.Final - https://netty.io/netty-codec-http2/)\r\n"
            + "    Netty/Codec/Socks (io.netty:netty-codec-socks:4.1.79.Final - https://netty.io/netty-codec-socks/)\r\n"
            + "    Netty/Common (io.netty:netty-common:4.1.79.Final - https://netty.io/netty-common/)\r\n"
            + "    Netty/Handler (io.netty:netty-handler:4.1.79.Final - https://netty.io/netty-handler/)\r\n"
            + "    Netty/Handler/Proxy (io.netty:netty-handler-proxy:4.1.79.Final - https://netty.io/netty-handler-proxy/)\r\n"
            + "    Netty/Resolver (io.netty:netty-resolver:4.1.79.Final - https://netty.io/netty-resolver/)\r\n"
            + "    Netty/Resolver/DNS (io.netty:netty-resolver-dns:4.1.79.Final - https://netty.io/netty-resolver-dns/)\r\n"
            + "    Netty/Resolver/DNS/Classes/MacOS (io.netty:netty-resolver-dns-classes-macos:4.1.79.Final - https://netty.io/netty-resolver-dns-classes-macos/)\r\n"
            + "    Netty/Resolver/DNS/Native/MacOS (io.netty:netty-resolver-dns-native-macos:4.1.79.Final - https://netty.io/netty-resolver-dns-native-macos/)\r\n"
            + "    Netty/Transport (io.netty:netty-transport:4.1.79.Final - https://netty.io/netty-transport/)\r\n"
            + "    Netty/Transport/Classes/Epoll (io.netty:netty-transport-classes-epoll:4.1.79.Final - https://netty.io/netty-transport-classes-epoll/)\r\n"
            + "    Netty/Transport/Native/Epoll (io.netty:netty-transport-native-epoll:4.1.79.Final - https://netty.io/netty-transport-native-epoll/)\r\n"
            + "    Netty/Transport/Native/Unix/Common (io.netty:netty-transport-native-unix-common:4.1.79.Final - https://netty.io/netty-transport-native-unix-common/)\r\n"
            + "    Non-Blocking Reactive Foundation for the JVM (io.projectreactor:reactor-core:3.4.21 - https://github.com/reactor/reactor-core)\r\n"
            + "    Core functionality for the Reactor Netty library (io.projectreactor.netty:reactor-netty-core:1.0.21 - https://github.com/reactor/reactor-netty)\r\n"
            + "    HTTP functionality for the Reactor Netty library (io.projectreactor.netty:reactor-netty-http:1.0.21 - https://github.com/reactor/reactor-netty)\r\n"
            + "    swagger-annotations (io.swagger.core.v3:swagger-annotations:2.2.9 - https://github.com/swagger-api/swagger-core/modules/swagger-annotations)\r\n"
            + "    swagger-core (io.swagger.core.v3:swagger-core:2.2.9 - https://github.com/swagger-api/swagger-core/modules/swagger-core)\r\n"
            + "    swagger-models (io.swagger.core.v3:swagger-models:2.2.9 - https://github.com/swagger-api/swagger-core/modules/swagger-models)\r\n"
            + "    Byte Buddy (without dependencies) (net.bytebuddy:byte-buddy:1.12.12 - https://bytebuddy.net/byte-buddy)\r\n"
            + "    Byte Buddy agent (net.bytebuddy:byte-buddy-agent:1.12.12 - https://bytebuddy.net/byte-buddy-agent)\r\n"
            + "    Failsafe (net.jodah:failsafe:2.4.4 - https://failsafe.dev)\r\n"
            + "    ASM based accessors helper used by json-smart (net.minidev:accessors-smart:2.4.8 - https://urielch.github.io/)\r\n"
            + "    JSON Small and Fast Parser (net.minidev:json-smart:2.4.8 - https://urielch.github.io/)\r\n"
            + "    Apache Commons Compress (org.apache.commons:commons-compress:1.23.0 - https://commons.apache.org/proper/commons-compress/)\r\n"
            + "    Apache Commons Lang (org.apache.commons:commons-lang3:3.12.0 - https://commons.apache.org/proper/commons-lang/)\r\n"
            + "    Apache Commons Math (org.apache.commons:commons-math3:3.6.1 - http://commons.apache.org/proper/commons-math/)\r\n"
            + "    Apache Log4j API (org.apache.logging.log4j:log4j-api:2.20.0 - https://logging.apache.org/log4j/2.x/log4j-api/)\r\n"
            + "    Apache Log4j to SLF4J Adapter (org.apache.logging.log4j:log4j-to-slf4j:2.17.2 - https://logging.apache.org/log4j/2.x/log4j-to-slf4j/)\r\n"
            + "    tomcat-embed-core (org.apache.tomcat.embed:tomcat-embed-core:9.0.65 - https://tomcat.apache.org/)\r\n"
            + "    tomcat-embed-el (org.apache.tomcat.embed:tomcat-embed-el:9.0.65 - https://tomcat.apache.org/)\r\n"
            + "    tomcat-embed-websocket (org.apache.tomcat.embed:tomcat-embed-websocket:9.0.65 - https://tomcat.apache.org/)\r\n"
            + "    org.apache.xmlgraphics:batik-anim (org.apache.xmlgraphics:batik-anim:1.16 - http://xmlgraphics.apache.org/batik/batik-anim/)\r\n"
            + "    org.apache.xmlgraphics:batik-awt-util (org.apache.xmlgraphics:batik-awt-util:1.16 - http://xmlgraphics.apache.org/batik/batik-awt-util/)\r\n"
            + "    org.apache.xmlgraphics:batik-bridge (org.apache.xmlgraphics:batik-bridge:1.16 - http://xmlgraphics.apache.org/batik/batik-bridge/)\r\n"
            + "    org.apache.xmlgraphics:batik-constants (org.apache.xmlgraphics:batik-constants:1.16 - http://xmlgraphics.apache.org/batik/batik-constants/)\r\n"
            + "    org.apache.xmlgraphics:batik-css (org.apache.xmlgraphics:batik-css:1.16 - http://xmlgraphics.apache.org/batik/batik-css/)\r\n"
            + "    org.apache.xmlgraphics:batik-dom (org.apache.xmlgraphics:batik-dom:1.16 - http://xmlgraphics.apache.org/batik/batik-dom/)\r\n"
            + "    org.apache.xmlgraphics:batik-ext (org.apache.xmlgraphics:batik-ext:1.16 - http://xmlgraphics.apache.org/batik/batik-ext/)\r\n"
            + "    org.apache.xmlgraphics:batik-gvt (org.apache.xmlgraphics:batik-gvt:1.16 - http://xmlgraphics.apache.org/batik/batik-gvt/)\r\n"
            + "    org.apache.xmlgraphics:batik-i18n (org.apache.xmlgraphics:batik-i18n:1.16 - http://xmlgraphics.apache.org/batik/batik-i18n/)\r\n"
            + "    org.apache.xmlgraphics:batik-parser (org.apache.xmlgraphics:batik-parser:1.16 - http://xmlgraphics.apache.org/batik/batik-parser/)\r\n"
            + "    org.apache.xmlgraphics:batik-script (org.apache.xmlgraphics:batik-script:1.16 - http://xmlgraphics.apache.org/batik/batik-script/)\r\n"
            + "    org.apache.xmlgraphics:batik-shared-resources (org.apache.xmlgraphics:batik-shared-resources:1.16 - http://xmlgraphics.apache.org/batik/batik-shared-resources/)\r\n"
            + "    org.apache.xmlgraphics:batik-svg-dom (org.apache.xmlgraphics:batik-svg-dom:1.16 - http://xmlgraphics.apache.org/batik/batik-svg-dom/)\r\n"
            + "    org.apache.xmlgraphics:batik-svggen (org.apache.xmlgraphics:batik-svggen:1.16 - http://xmlgraphics.apache.org/batik/batik-svggen/)\r\n"
            + "    org.apache.xmlgraphics:batik-transcoder (org.apache.xmlgraphics:batik-transcoder:1.16 - http://xmlgraphics.apache.org/batik/batik-transcoder/)\r\n"
            + "    org.apache.xmlgraphics:batik-util (org.apache.xmlgraphics:batik-util:1.16 - http://xmlgraphics.apache.org/batik/batik-util/)\r\n"
            + "    org.apache.xmlgraphics:batik-xml (org.apache.xmlgraphics:batik-xml:1.16 - http://xmlgraphics.apache.org/batik/batik-xml/)\r\n"
            + "    Apache XML Graphics Commons (org.apache.xmlgraphics:xmlgraphics-commons:2.7 - http://xmlgraphics.apache.org/commons/)\r\n"
            + "    org.apiguardian:apiguardian-api (org.apiguardian:apiguardian-api:1.1.2 - https://github.com/apiguardian-team/apiguardian)\r\n"
            + "    AssertJ fluent assertions (org.assertj:assertj-core:3.22.0 - https://assertj.github.io/doc/assertj-core/)\r\n"
            + "    Java Annotation Indexer (org.jboss:jandex:2.4.2.Final - http://www.jboss.org/jandex)\r\n"
            + "    JBoss Logging 3 (org.jboss.logging:jboss-logging:3.4.3.Final - http://www.jboss.org)\r\n"
            + "    Objenesis (org.objenesis:objenesis:3.3 - http://objenesis.org/objenesis)\r\n"
            + "    org.opentest4j:opentest4j (org.opentest4j:opentest4j:1.2.0 - https://github.com/ota4j-team/opentest4j)\r\n"
            + "    JSONassert (org.skyscreamer:jsonassert:1.5.1 - https://github.com/skyscreamer/JSONassert)\r\n"
            + "    springdoc-openapi-common (org.springdoc:springdoc-openapi-common:1.7.0 - https://springdoc.org/springdoc-openapi-common/)\r\n"
            + "    springdoc-openapi-ui (org.springdoc:springdoc-openapi-ui:1.7.0 - https://springdoc.org/springdoc-openapi-ui/)\r\n"
            + "    springdoc-openapi-webmvc-core (org.springdoc:springdoc-openapi-webmvc-core:1.7.0 - https://springdoc.org/springdoc-openapi-webmvc-core/)\r\n"
            + "    Spring AOP (org.springframework:spring-aop:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring Aspects (org.springframework:spring-aspects:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring Beans (org.springframework:spring-beans:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring Context (org.springframework:spring-context:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring Core (org.springframework:spring-core:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring Expression Language (SpEL) (org.springframework:spring-expression:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring Commons Logging Bridge (org.springframework:spring-jcl:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring JDBC (org.springframework:spring-jdbc:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring Messaging (org.springframework:spring-messaging:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring Object/Relational Mapping (org.springframework:spring-orm:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring Transaction (org.springframework:spring-tx:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring Web (org.springframework:spring-web:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring WebFlux (org.springframework:spring-webflux:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring Web MVC (org.springframework:spring-webmvc:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    Spring WebSocket (org.springframework:spring-websocket:5.3.22 - https://github.com/spring-projects/spring-framework)\r\n"
            + "    spring-boot (org.springframework.boot:spring-boot:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-actuator (org.springframework.boot:spring-boot-actuator:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-actuator-autoconfigure (org.springframework.boot:spring-boot-actuator-autoconfigure:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-autoconfigure (org.springframework.boot:spring-boot-autoconfigure:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-configuration-processor (org.springframework.boot:spring-boot-configuration-processor:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-devtools (org.springframework.boot:spring-boot-devtools:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-loader (org.springframework.boot:spring-boot-loader:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-starter (org.springframework.boot:spring-boot-starter:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-starter-actuator (org.springframework.boot:spring-boot-starter-actuator:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-starter-aop (org.springframework.boot:spring-boot-starter-aop:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-starter-data-jpa (org.springframework.boot:spring-boot-starter-data-jpa:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-starter-jdbc (org.springframework.boot:spring-boot-starter-jdbc:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-starter-json (org.springframework.boot:spring-boot-starter-json:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-starter-logging (org.springframework.boot:spring-boot-starter-logging:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-starter-reactor-netty (org.springframework.boot:spring-boot-starter-reactor-netty:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-starter-test (org.springframework.boot:spring-boot-starter-test:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-starter-tomcat (org.springframework.boot:spring-boot-starter-tomcat:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-starter-web (org.springframework.boot:spring-boot-starter-web:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-starter-webflux (org.springframework.boot:spring-boot-starter-webflux:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-test (org.springframework.boot:spring-boot-test:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    spring-boot-test-autoconfigure (org.springframework.boot:spring-boot-test-autoconfigure:2.7.2 - https://spring.io/projects/spring-boot)\r\n"
            + "    Spring Data Core (org.springframework.data:spring-data-commons:2.7.2 - https://www.spring.io/spring-data/spring-data-commons)\r\n"
            + "    Spring Data JPA (org.springframework.data:spring-data-jpa:2.7.2 - https://spring.io/projects/spring-data-jpa)\r\n"
            + "    Swagger UI (org.webjars:swagger-ui:4.18.2 - http://webjars.org)\r\n"
            + "    org.xmlunit:xmlunit-core (org.xmlunit:xmlunit-core:2.9.0 - https://www.xmlunit.org/)\r\n"
            + "    SnakeYAML (org.yaml:snakeyaml:1.30 - https://bitbucket.org/snakeyaml/snakeyaml)\r\n"
            + "    (The SAX License) (The W3C License) XML Commons External Components XML APIs (xml-apis:xml-apis:1.4.01 - http://xml.apache.org/commons/components/external/)\r\n"
            + "    XML Commons External Components XML APIs Extensions (xml-apis:xml-apis-ext:1.3.04 - http://xml.apache.org/commons/components/external/)\r\n"
            + "\r\n"
            + "(BSD License)\r\n"
            + "    AntLR Parser Generator (antlr:antlr:2.7.7 - http://www.antlr.org/)\r\n"
            + "\r\n"
            + "(BSD-2-Clause) (Creative Commons CC0)\r\n"
            + "    HdrHistogram (org.hdrhistogram:HdrHistogram:2.1.12 - http://hdrhistogram.github.io/HdrHistogram/) \r\n"
            + "\r\n"
            + "(BSD License 3)\r\n"
            + "    Hamcrest (org.hamcrest:hamcrest:2.2 - http://hamcrest.org/JavaHamcrest/)\r\n"
            + "    asm (org.ow2.asm:asm:9.1 - http://asm.ow2.io/)\r\n"
            + "\r\n"
            + "(Creative Commons CC0)\r\n"
            + "    LatencyUtils (org.latencyutils:LatencyUtils:2.0.3 - http://latencyutils.github.io/LatencyUtils/)\r\n"
            + "\r\n"
            + "(Eclipse Distribution License - v 1.0)\r\n"
            + "    Jakarta XML Binding API (jakarta.xml.bind:jakarta.xml.bind-api:2.3.3 - https://github.com/eclipse-ee4j/jaxb-api/jakarta.xml.bind-api)\r\n"
            + "    JAXB Runtime (org.glassfish.jaxb:jaxb-runtime:2.3.6 - https://eclipse-ee4j.github.io/jaxb-ri/)\r\n"
            + "    TXW2 Runtime (org.glassfish.jaxb:txw2:2.3.6 - https://eclipse-ee4j.github.io/jaxb-ri/)\r\n"
            + "\r\n"
            + "(Eclipse Public License - v 1.0) (GNU Lesser General Public License)\r\n"
            + "    Logback Classic Module (ch.qos.logback:logback-classic:1.2.11 - http://logback.qos.ch/logback-classic)\r\n"
            + "    Logback Core Module (ch.qos.logback:logback-core:1.2.11 - http://logback.qos.ch/logback-core)\r\n"
            + "    istack common utility code runtime (com.sun.istack:istack-commons-runtime:3.0.12 - https://projects.eclipse.org/projects/ee4j/istack-commons/istack-commons-runtime)\r\n"
            + "\r\n"
            + "(Eclipse Distribution License - v 1.0) (Eclipse Public License - v 1.0)\r\n"
            + "    Eclipse Collections API (org.eclipse.collections:eclipse-collections-api:11.1.0 - https://github.com/eclipse/eclipse-collections/eclipse-collections-api)\r\n"
            + "    Eclipse Collections API (org.eclipse.collections:eclipse-collections-api:11.1.0 - https://github.com/eclipse/eclipse-collections/eclipse-collections-api)\r\n"
            + "\r\n"
            + "(Eclipse Distribution License v. 1.0) (Eclipse Public License v. 2.0)\r\n"
            + "    Jakarta Persistence API (jakarta.persistence:jakarta.persistence-api:2.2.3 - https://github.com/eclipse-ee4j/jpa-api)\r\n"
            + "    Eclipse Collections Main Library (org.eclipse.collections:eclipse-collections:11.1.0 - https://github.com/eclipse/eclipse-collections/eclipse-collections)\r\n"
            + "    org.locationtech.jts:jts-core (org.locationtech.jts:jts-core:1.19.0 - https://www.locationtech.org/projects/technology.jts/jts-modules/jts-core)\r\n"
            + "    org.locationtech.jts.io:jts-io-common (org.locationtech.jts.io:jts-io-common:1.19.0 - https://www.locationtech.org/projects/technology.jts/jts-modules/jts-io/jts-io-common)\r\n"
            + "\r\n"
            + "(Eclipse Public License - v 2.0)\r\n"
            + "    AspectJ Weaver (org.aspectj:aspectjweaver:1.9.7 - https://www.eclipse.org/aspectj/)\r\n"
            + "    JUnit Jupiter (Aggregator) (org.junit.jupiter:junit-jupiter:5.9.2 - https://junit.org/junit5/)\r\n"
            + "    JUnit Jupiter API (org.junit.jupiter:junit-jupiter-api:5.8.2 - https://junit.org/junit5/)\r\n"
            + "    JUnit Jupiter Engine (org.junit.jupiter:junit-jupiter-engine:5.8.2 - https://junit.org/junit5/)\r\n"
            + "    JUnit Jupiter Params (org.junit.jupiter:junit-jupiter-params:5.8.2 - https://junit.org/junit5/)\r\n"
            + "    JUnit Platform Commons (org.junit.platform:junit-platform-commons:1.8.2 - https://junit.org/junit5/)\r\n"
            + "    JUnit Platform Engine API (org.junit.platform:junit-platform-engine:1.8.2 - https://junit.org/junit5/)\r\n"
            + "\r\n"
            + "(Eclipse Public License 2.0) (GNU General Public License, version 2 with the GNU Classpath Exception)\r\n"
            + "    Tyrus Standalone Client (org.glassfish.tyrus.bundles:tyrus-standalone-client:1.20 - https://projects.eclipse.org/projects/ee4j.tyrus/tyrus-bundles/tyrus-standalone-client)\r\n"
            + "\r\n"
            + "(EPL 1.0) (MPL 2.0)\r\n"
            + "    H2 Database Engine (com.h2database:h2:2.1.214 - https://h2database.com)\r\n"
            + "    Jakarta Annotations API (jakarta.annotation:jakarta.annotation-api:1.3.5 - https://projects.eclipse.org/projects/ee4j.ca)\r\n"
            + "\r\n"
            + "(EDL 1.0)\r\n"
            + "    Jakarta Activation (com.sun.activation:jakarta.activation:1.2.2 - https://github.com/eclipse-ee4j/jaf/jakarta.activation)\r\n"
            + "    Jakarta Activation API jar (jakarta.activation:jakarta.activation-api:1.2.2 - https://github.com/eclipse-ee4j/jaf/jakarta.activation-api)\r\n"
            + "\r\n"
            + "(EPL 2.0)\r\n"
            + "    Jakarta Annotations API (jakarta.annotation:jakarta.annotation-api:1.3.5 - https://projects.eclipse.org/projects/ee4j.ca)\r\n"
            + "    javax.transaction API (jakarta.transaction:jakarta.transaction-api:1.3.3 - https://projects.eclipse.org/projects/ee4j.jta)\r\n"
            + "\r\n"
            + "(GNU Library General Public License v2.1 or later)\r\n"
            + "    Hibernate ORM - hibernate-core (org.hibernate:hibernate-core:5.6.10.Final - https://hibernate.org/orm)\r\n"
            + "    Hibernate Commons Annotations (org.hibernate.common:hibernate-commons-annotations:5.1.2.Final - http://hibernate.org)\r\n"
            + "\r\n"
            + "(MIT-0)\r\n"
            + "    reactive-streams (org.reactivestreams:reactive-streams:1.0.4 - http://www.reactive-streams.org/)\r\n"
            + "\r\n"
            + "(The MIT License(MIT))\r\n"
            + "    Java implementation of GeographicLib (net.sf.geographiclib:GeographicLib-Java:2.0 - https://geographiclib.sourceforge.io)\r\n"
            + "    Checker Qual (org.checkerframework:checker-qual:3.12.0 - https://checkerframework.org)\r\n"
            + "    mockito-core (org.mockito:mockito-core:5.2.0 - https://github.com/mockito/mockito)\r\n"
            + "    mockito-junit-jupiter (org.mockito:mockito-junit-jupiter:5.2.0 - https://github.com/mockito/mockito)\r\n"
            + "    JUL to SLF4J bridge (org.slf4j:jul-to-slf4j:1.7.36 - http://www.slf4j.org)\r\n"
            + "    SLF4J API Module (org.slf4j:slf4j-api:1.7.36 - http://www.slf4j.org)\r\n"
            + "    jts2geojson (org.wololo:jts2geojson:0.18.1 - https://github.com/bjornharrtell/jts2geojson)\r\n";

}
