# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload standalone to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: calibration-standalone/target/calibration-standalone-*-runnable.jar
        tag: ${{ github.ref }}
        overwrite: true     
        file_glob: true

    - name: Upload application to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: calibration-service/calibration-application/target/calibration-application-*-runnable.jar
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        
    - name: Upload ratios to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: calibration-standalone/target/calibration-standalone-*-ratios.jar
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true

    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: mvn deploy
